# Parameters related to building rocalution
ARG base_image

FROM ${base_image}
MAINTAINER Nico Trost

# Copy the rpm package of rocalution into the container from host
COPY *.rpm /tmp/

# Install the rpm package, and print out contents of expected changed locations
RUN yum -y update && yum install -y\
    /tmp/rocalution-*.rpm \
  && rm -f /tmp/*.rpm \
  && yum -y clean all \
  && rm -rf /var/lib/apt/lists/* \
  && printf "ls -la /etc/ld.so.conf.d/\n" && ls -la /etc/ld.so.conf.d/ \
  && printf "ls -la /opt/rocm/include\n" && ls -la /opt/rocm/include \
  && printf "ls -la /opt/rocm/lib\n" && ls -la /opt/rocm/lib \
  && printf "ls -la /opt/rocm/lib/cmake\n" && ls -la /opt/rocm/lib/cmake \
  && printf "ls -la /opt/rocm/rocalution/include\n" && ls -la /opt/rocm/rocalution/include \
  && printf "ls -la /opt/rocm/rocalution/lib\n" && ls -la /opt/rocm/rocalution/lib
