# Parameters related to building rocALUTION
ARG base_image

FROM ${base_image}
LABEL maintainer="rocalution-maintainer@amd.com"

ARG user_uid
ARG library_dependencies="rocblas rocprim rocsparse"

# Install dependent packages
# Dependencies:
# * hcc-config.cmake: pkg-config
# * rocalution: rocblas rocprim rocrand rocsparse openmp
# * rocalution_mpi: mpi-default-bin mpi-default-dev
# * rocalution-test: googletest
# * rocalution-bench: libboost-program-options-dev
# * libhsakmt.so: libnuma1
RUN zypper refresh && zypper -n --no-gpg-checks install \
    sudo \
    mpich \
    mpich-devel \
    ca-certificates \
    git \
    make \
    cmake \
    gcc-c++ \
    pkg-config \
    dpkg \
    libcxxtools9 \
    libboost_program_options1_66_0-devel \
    libnuma1 \
    rpm-build \
    wget \
    unzip \
    ${library_dependencies}

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G video --shell /bin/bash jenkins && \
    echo '%video ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    chmod 400 /etc/sudoers.d/sudo-nopasswd

ARG ROCALUTION_SRC_ROOT=/usr/local/src/rocALUTION

# Clone rocalution repo
# Build client dependencies and install into /usr/local
RUN mkdir -p ${ROCALUTION_SRC_ROOT} && cd ${ROCALUTION_SRC_ROOT} && \
    git clone -b develop --depth=1 https://github.com/ROCmSoftwarePlatform/rocALUTION . && \
    mkdir -p build/deps && cd build/deps && \
    cmake ${ROCALUTION_SRC_ROOT}/deps && \
    make -j $(nproc) install && \
    rm -rf ${ROCALUTION_SRC_ROOT}
