# Parameters related to building rocALUTION
ARG base_image

FROM ${base_image}
MAINTAINER Nico Trost

ARG user_uid

# Install dependent packages
# Dependencies:
# * hcc-config.cmake: pkg-config
# * rocalution: rocblas rocrand rocsparse openmp
# * rocalution_mpi: mpi-default-bin mpi-default-dev
# * rocalution-test: googletest
# * rocalution-bench: libboost-program-options-dev
# * libhsakmt.so: libnuma1
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    rock-dkms \
    sudo \
    mpi-default-bin \
    mpi-default-dev \
    libomp-dev \
    libomp5 \
    build-essential \
    ca-certificates \
    git \
    make \
    cmake \
    clang-format-3.8 \
    pkg-config \
    libboost-program-options-dev \
    libnuma1 \
    wget \
    rocblas \
    rocrand

# Add rocm repository
#RUN wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | apt-key add -
#RUN sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
#RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
#    rocblas \
#    rocrand \
#    && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/*

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G sudo --shell /bin/bash jenkins && \
    mkdir -p /etc/sudoers.d/ && \
    echo '%sudo   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    echo 'jenkins ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd
