# Parameters related to building rocALUTION
ARG base_image

FROM ${base_image}
MAINTAINER Nico Trost

ARG user_uid

# Install dependent packages
# Dependencies:
# * hcc-config.cmake: pkg-config
# * rocalution: rocblas rocrand rocsparse openmp
# * rocalution_mpi: mpi-default-bin mpi-default-dev
# * rocalution-test: googletest
# * rocalution-bench: libboost-program-options-dev
# * libhsakmt.so: libnuma1
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    rock-dkms \
    sudo \
    mpi-default-bin \
    mpi-default-dev \
    libomp-dev \
    libomp5 \
    build-essential \
    ca-certificates \
    git \
    make \
    cmake \
    clang-format-3.8 \
    pkg-config \
    libboost-program-options-dev \
    libnuma1 \
    rocblas \
    rocsparse \
    rocrand \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G sudo --shell /bin/bash jenkins && \
    mkdir -p /etc/sudoers.d/ && \
    echo '%sudo   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd

ARG ROCSPARSE_SRC_ROOT=/usr/local/src/rocSPARSE
ARG ROCALUTION_SRC_ROOT=/usr/local/src/rocALUTION

# Clone rocsparse repo
# Build rocsparse and install into /usr/local
RUN mkdir -p ${ROCSPARSE_SRC_ROOT} && cd ${ROCSPARSE_SRC_ROOT} && \
    git clone -b master-rocm-2.5 --depth=1 https://github.com/ROCmSoftwarePlatform/rocSPARSE . && \
    mkdir -p build && cd build && \
    HIP_PLATFORM=hcc cmake -DBUILD_CLIENTS_SAMPLES=OFF .. && \
    HIP_PLATFORM=hcc make -j $(nproc) install && \
    rm -rf ${ROCSPARSE_SRC_ROOT}

# Clone rocalution repo
# Build client dependencies and install into /usr/local
RUN mkdir -p ${ROCALUTION_SRC_ROOT} && cd ${ROCALUTION_SRC_ROOT} && \
    git clone -b master-rocm-2.5 --depth=1 https://github.com/ROCmSoftwarePlatform/rocALUTION . && \
    mkdir -p build/deps && cd build/deps && \
    HIP_PLATFORM=hcc cmake -DBUILD_BOOST=OFF ${ROCALUTION_SRC_ROOT}/deps && \
    HIP_PLATFORM=hcc make -j $(nproc) install && \
    rm -rf ${ROCALUTION_SRC_ROOT}
