resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

# Pipeline disabled: rocALUTION depends on rocsparse (disabled)
trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocALUTION.yml@pipelines_repo
