#ifndef ROCALUTION_VERSION_HPP_
#define ROCALUTION_VERSION_HPP_

// VERSION
#define __ROCALUTION_VER_TYPE "M"

#define __ROCALUTION_VER_MAJOR 1
#define __ROCALUTION_VER_MINOR 3
#define __ROCALUTION_VER_REV  0

// BETA or ALPHA
//#define __ROCALUTION_VER_PRE ""
#define __ROCALUTION_VER_PRE "ALPHA"
//#define __ROCALUTION_VER_PRE "BETA"

#define __ROCALUTION_VER 10000*__ROCALUTION_VER_MAJOR+100*__ROCALUTION_VER_MINOR+__ROCALUTION_VER_REV


#endif // ROCALUTION_VERSION_HPP_
