#ifndef PARALUTION_VERSION_HPP_
#define PARALUTION_VERSION_HPP_

// VERSION
#define __PARALUTION_VER_TYPE "M"

#define __PARALUTION_VER_MAJOR 1
#define __PARALUTION_VER_MINOR 2
#define __PARALUTION_VER_REV  0

// BETA or ALPHA
#define __PARALUTION_VER_PRE ""
//#define __PARALUTION_VER_PRE "ALPHA"
//#define __PARALUTION_VER_PRE "BETA"

#define __PARALUTION_VER 10000*__PARALUTION_VER_MAJOR+100*__PARALUTION_VER_MINOR+__PARALUTION_VER_REV


#endif // PARALUTION_VERSION_HPP_
